remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Compassion One
description: Compassion One App Terms of Service and Privacy Policy

show_downloads: true

github:
  zip_url: https://successirabor.github.io/Compassion-One/Compassion%20One%20Terms%20of%20Service%20Agreement.pdf
  tar_url: https://successirabor.github.io/Compassion-One/Compassion%20One%20Privacy%20Policy.pdf
